public enum EClipIndex
{
    JUMP = 0,

    JUMP_LANDING, 
    MANITE_DASH,

    MANITE_SLASH, 
    NORMAL_ATTACK,

    FOOTSTEPS_WOOD_WALK_1, 
    FOOTSTEPS_WOOD_WALK_2,

    FOOTSTEPS_WOOD_RUN_1, 
    FOOTSTEPS_WOOD_RUN_2,

    FOOTSTEPS_ROCK_WALK_1, 
    FOOTSTEPS_ROCK_WALK_2,

    FOOTSTEPS_ROCK_RUN_1, 
    FOOTSTEPS_ROCK_RUN_2
}