public enum EClipIndex
{
    DICE_ROLL = 0,

    FOOTSTEPS_GROUND_WALK_1, 
    FOOTSTEPS_GROUND_WALK_2,

    FOOTSTEPS_GROUND_RUN_1, 
    FOOTSTEPS_GROUND_RUN_2,

    FOOTSTEPS_WOOD_WALK_1, 
    FOOTSTEPS_WOOD_WALK_2,

    FOOTSTEPS_WOOD_RUN_1, 
    FOOTSTEPS_WOOD_RUN_2,

    FOOTSTEPS_ROCK_WALK_1, 
    FOOTSTEPS_ROCK_WALK_2,

    FOOTSTEPS_ROCK_RUN_1, 
    FOOTSTEPS_ROCK_RUN_2
}